### ISSUE TITLE
Dashboard Token Listing: USDCx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#100]
Discord Handle of Submitter: Elvijs Dzirkals #1408

Token Symbol: USDCx

Network: Binance Smart Chain

Token Address: 0x0419e1fa3671754f77ec7d5416219a5f9a08b530

Network Explorer Link: https://www.bscscan.com/address/0x0419e1fa3671754f77ec7d5416219a5f9a08b530

Is a Super Token? true

Address of Underlying Token:  0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d

SVG Logo Link: Re-use the USDC one

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: Re-use the USDC one

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: Re-use the USDC one

Info on Listing: Need this for testing

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/bnb-smart-chain/supertokens/0x0419e1fa3671754f77ec7d5416219a5f9a08b530?tab=streams
