### ISSUE TITLE
Dashboard Token Listing: ABT 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#104]
Discord Handle of Submitter: jont#5021

Token Symbol: ABT

Network: Optimism

Token Address: 0x4Ee43F45acC85271889F12C4BdAdE35FdC131481

Network Explorer Link: https://optimistic.etherscan.io/address/0x4Ee43F45acC85271889F12C4BdAdE35FdC131481

Is a Super Token? true

Address of Underlying Token:  none

SVG Logo Link: https://anotherblockwebsite.s3.eu-north-1.amazonaws.com/logo.svg

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): 0

Token HEX Color: #000000

Info on Listing: when owning anotherblock NFTs you earn extra ABT tokens that are soulbound to be used in our utility store

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
As clarified via Telegram, the token intended for listing is 0x167832BAF36D1AC0aF9e8d8aD329Fa418BeD5cD9.
Listing done: https://console.superfluid.finance/optimism-mainnet/supertokens/0x167832BAF36D1AC0aF9e8d8aD329Fa418BeD5cD9?tab=streams

@vmichalik pls approve https://github.com/superfluid-finance/assets/pull/107
