### ISSUE TITLE
Dashboard Token Listing: AGOLD 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#108]
Discord Handle of Submitter: Fran | Superfluid

Token Symbol: AGOLD

Network: Polygon

Token Address: 0xFAc83774854237b6E31c4B051b91015e403956d3

Network Explorer Link: https://polygonscan.com/address/0xfac83774854237b6e31c4b051b91015e403956d3

Is a Super Token? true

Address of Underlying Token:  0xe06bd4f5aac8d0aa337d13ec88db6defc6eaeefe

SVG Logo Link: https://drive.google.com/file/d/1r3Hf8ME3cd3UhL1pXvivK7gFvmf8Gi_P/view?usp=sharing

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/ix-token

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #ffb429

Info on Listing: It's not following a naming convention. 
The normal token is called $IXT, the Super Token is called $AGOLD

The normal token's logo can be found on the coingecko link above

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
Listed: https://console.superfluid.finance/matic/supertokens/0xFAc83774854237b6E31c4B051b91015e403956d3?tab=streams

@kobuta23 pls check/approve/merge https://github.com/superfluid-finance/assets/pull/109
