### ISSUE TITLE
Dashboard Token Listing: AMKT 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#110]
Discord Handle of Submitter: groms#7279

Token Symbol: AMKT

Network: Polygon

Token Address: 0xB87904DB461005FC716a6BF9F2d451c33b10b80b

Network Explorer Link: https://polygonscan.com/token/0xb87904db461005fc716a6bf9f2d451c33b10b80b

Is a Super Token? true

Address of Underlying Token:  https://polygonscan.com/token/0x5d6fdc854b46e8b237bd2ccc2714cfa3d18cf58e

SVG Logo Link: https://s2.coinmarketcap.com/static/img/coins/64x64/22999.png

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: alongside-crypto-market-index

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #0c0c0c

Info on Listing: AMKT is a crypto index. We think superfluid is an amazing way to DCA into tokens, so naturally people would want to use it to buy and index (and thus the market). We are Alongside, you can learn more at https://alongside.xyz.

If you have any questions, feel free to reach out at James@alongside.xyz.

Thank you :)

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/matic/supertokens/0x5d6Fdc854b46e8B237bd2cCC2714cFA3D18cF58E?tab=streams
(0x5d6Fdc854b46e8B237bd2cCC2714cFA3D18cF58E is the SuperToken address, 0xb87904db461005fc716a6bf9f2d451c33b10b80b is the address of the underlying.

Asset PR: https://github.com/superfluid-finance/assets/pull/111
