### ISSUE TITLE
Dashboard Token Listing: jMXNx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#112]
Discord Handle of Submitter: Pascal | jarvis.network#2347

Token Symbol: jMXNx

Network: Polygon

Token Address: 0x64059efad287b57d8df9c313d56f6c1a5c945b94

Network Explorer Link: https://polygonscan.com/token/0x64059efad287b57d8df9c313d56f6c1a5c945b94

Is a Super Token? true

Address of Underlying Token:  0xbd1fe73e1f12bd2bc237de9b626f056f21f86427

SVG Logo Link: https://268666614-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MeLxeE9i1iOeDR_J-tQ%2Fuploads%2FpLW4J9fTSdQBIVCKXLQ5%2FjMXN%20(3).svg?alt=media&token=02991810-b5f8-45ee-824d-df24271c15a0

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): 1 MXN

Token HEX Color: #056443

Info on Listing: Pay salary in Mexico

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/matic/supertokens/0x64059efad287b57d8df9c313d56f6c1a5c945b94?tab=streams
@msoni89 please add the assets

**Comment by msoni89** [comment]
Closing, already added
