### ISSUE TITLE
Dashboard Token Listing: OPx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#113]
Discord Handle of Submitter: Sero#0676

Token Symbol: OPx

Network: Optimism

Token Address: 0x1828Bff08BD244F7990edDCd9B19cc654b33cDB4

Network Explorer Link: https://optimistic.etherscan.io/token/0x1828bff08bd244f7990eddcd9b19cc654b33cdb4

Is a Super Token? true

Address of Underlying Token:  0x4200000000000000000000000000000000000042

SVG Logo Link: https://optimistic.etherscan.io/images/logo-ether.svg?v=0.0.4

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/optimism

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #fc0727

Info on Listing: This is OP supertoken

Please close only after token has been added to resolver!

**Comment by Seroxdesign** [comment]
I would like to deploy this for our app

**Comment by d10r** [comment]
thx for the deployment
listing done: https://console.superfluid.finance/optimism-mainnet/supertokens/0x1828bff08bd244f7990eddcd9b19cc654b33cdb4?tab=streams

@msoni89 please add the assets

**Comment by msoni89** [comment]
Closing, already added
