### ISSUE TITLE
Dashboard Token Listing: WMATICx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#118]
Discord Handle of Submitter: omnifient | BTFDCA.finance#7921

Token Symbol: WMATICx

Network: Polygon

Token Address: 0xe04ad5d86c40d53a12357e1ba2a9484f60db0da5

Network Explorer Link: https://polygonscan.com/address/0xe04ad5d86c40d53a12357e1ba2a9484f60db0da5

Is a Super Token? true

Address of Underlying Token:  0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270

SVG Logo Link: https://polygontechnology.notion.site/d20ce41c09304676814f4187eb85db94?v=01167fbffe6d41e1a574d4ee5f33274d

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: polygon

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #803ce0

Info on Listing: I'm requesting this listing because BTFDCA has added WMATICx as an asset, and it would be nice for holders to see it on the Superfluid App.

Note that this is a wrapper supertoken for WMATIC (downgrades to WMATIC), which is different from MATICx.

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/matic/supertokens/0xe04ad5d86c40d53a12357E1Ba2A9484F60DB0da5

@msoni89 please add assets
