### ISSUE TITLE
Dashboard Token Listing: CRVx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#119]
Discord Handle of Submitter: omnifient | BTFDCA.finance#7921

Token Symbol: CRVx

Network: Polygon

Token Address: 0x96eac3913bab431c28895f02cf5c56ad2dab8439

Network Explorer Link: https://polygonscan.com/address/0x96eac3913bab431c28895f02cf5c56ad2dab8439

Is a Super Token? true

Address of Underlying Token:  0x172370d5cd63279efa6d502dab29171933a610af

SVG Logo Link: https://2254922201-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MFA0rQI3SzfbVFgp3Ic%2Fuploads%2FF5ZS9RzAWKZnNxm9F85H%2FCurve-Logo-HighRez.png?alt=media&token=51c58ab0-e774-4b30-92ac-69f643400c56

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: curve-dao-token

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #ffe600

Info on Listing: I'm requesting this listing because BTFDCA has added CRVx as an asset, and it would be nice for holders to see it on the Superfluid App.

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/matic/supertokens/0x96Eac3913BAB431c28895F02CF5c56Ad2DaB8439?tab=streams

@msoni89 please add assets
