### ISSUE TITLE
Dashboard Token Listing: GNSx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#120]
Discord Handle of Submitter: omnifient | BTFDCA.finance#7921

Token Symbol: GNSx

Network: Polygon

Token Address: 0xfd0577c4707367ff9b637f219388919d3be37592

Network Explorer Link: https://polygonscan.com/address/0xfd0577c4707367ff9b637f219388919d3be37592

Is a Super Token? true

Address of Underlying Token:  0xe5417af564e4bfda1c483642db72007871397896

SVG Logo Link: https://avatars.githubusercontent.com/u/8012606?v=4

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: gains-network

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #42eda7

Info on Listing: I'm requesting this listing because BTFDCA has added GNSx as an asset, and it would be nice for holders to see it on the Superfluid App.

Please close only after token has been added to resolver!

**Comment by msoni89** [comment]
@vmichalik

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/matic/supertokens/0xfD0577C4707367ff9B637F219388919d3Be37592?tab=streams

@msoni89 please add assets
