### ISSUE TITLE
Dashboard Token Listing: SBCx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#127]
Discord Handle of Submitter: KyngKai 界王#6521

Token Symbol: SBCx

Network: Gnosis Chain

Token Address: 0x7C78aA599bBaeA6e8784880173Eb74B2F9c46025

Network Explorer Link: https://gnosisscan.io/token/0x7c78aa599bbaea6e8784880173eb74b2f9c46025

Is a Super Token? true

Address of Underlying Token:  0x3b6a1B76D772a771bf3fCe802BeaD6Ff196B84d5

SVG Logo Link: https://lh5.googleusercontent.com/-z9x_do2hrWU/AAAAAAAAAAI/AAAAAAAAAAA/VfR_biBSvAs/s88-p-k-no-ns-nd/photo.jpg

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): .10

Token HEX Color: 0e0e0e

Info on Listing: Our token is a Colony issued governance token. We our listing our token in order to complete fair distributions of our token to early community members so we can bootstrap governance within the DAO.

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/xdai/supertokens/0x7C78aA599bBaeA6e8784880173Eb74B2F9c46025?tab=streams

@msoni89 please add assets
