### ISSUE TITLE
Dashboard Token Listing: RB 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#129]
Discord Handle of Submitter: demoniccil#1448

Token Symbol: RB

Network: Binance Smart Chain

Token Address: 0x744786AB00ED5A0B77cA754EB6f3eC0607c7Fa79

Network Explorer Link: https://bscscan.com/token/0x744786ab00ed5a0b77ca754eb6f3ec0607c7fa79

Is a Super Token? true

Address of Underlying Token:  0x441Bb79F2da0dAF457BaD3d401eDb68535fB3faa

SVG Logo Link: https://www.dropbox.com/s/wdz10wwnnfif98r/rebornlogo.svg?dl=0

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): $0.072

Token HEX Color: #fc833a

Info on Listing: Website: http://re-born.company
New website (demo): http://re-born.webflow.io
Twitter: https://twitter.com/Re_bornofficial
Whitepaper: https://re-born.gitbook.io/hey-re-born-whitepaper-2.0
Reason for listing: To use vesting platform on Superfluid.

Please close only after token has been added to resolver!

**Comment by cilmion** [comment]
You can also contact me on Telegram: @demoniccil

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/bnb-smart-chain/supertokens/0x744786AB00ED5A0B77cA754EB6f3eC0607c7Fa79?tab=streams
