### ISSUE TITLE
Dashboard Token Listing: STAK 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#131]
Discord Handle of Submitter: andrea0x.eth#0001

Token Symbol: STAK

Network: Polygon

Token Address: 0x46A5D492788f8AFdfC743Ab7D7bD13F996249ED5

Network Explorer Link: https://polygonscan.com/token/0x46a5d492788f8afdfc743ab7d7bd13f996249ed5

Is a Super Token? true

Address of Underlying Token:  0x2B47eE85a85b18BE029af94DF52fCB52c54725F4

SVG Logo Link: https://assets.coingecko.com/coins/images/14978/small/jigstack.PNG?1619216498

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/it/monete/jigstack

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #5957d7

Info on Listing: DAO payment management (I had a chat with Francesco)

Please close only after token has been added to resolver!

**Comment by msoni89** [comment]
@d10r FYI  Filled wrong info - 0x2B47eE85a85b18BE029af94DF52fCB52c54725F4 (super token address), 0x46A5D492788f8AFdfC743Ab7D7bD13F996249ED5 -  underlying token

**Comment by vmichalik** [comment]
completed
