### ISSUE TITLE
Dashboard Token Listing: WARU 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#133]
Discord Handle of Submitter: biosensei#7599

Token Symbol: WARU

Network: Polygon

Token Address: 0xE3627374Ac4baf5375e79251B0af23aFc450FC0E

Network Explorer Link: https://polygonscan.com/token/0xe3627374ac4baf5375e79251b0af23afc450fc0e

Is a Super Token? false

Address of Underlying Token:  

SVG Logo Link: https://www.waruprotocol.one/assets/logo.94e2b55c.png

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.geckoterminal.com/polygon_pos/pools/0x017fe2f89a34a3485b66e50b3b25c588d70a787a?utm_source=coingecko&utm_medium=referral&utm_campaign=searchresults

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #58c58e

Info on Listing: stream WARU to NFT holders

Please close only after token has been added to resolver!

**Comment by vmichalik** [comment]
Doesn't appear to be a Super Token on wrapper, will message the issue creator

**Comment by vmichalik** [comment]
Issue creator discord handle doesn't work
