### ISSUE TITLE
Dashboard Token Listing: ANTx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#134]
Discord Handle of Submitter: ricktik6#0196

Token Symbol: ANTx

Network: Ethereum Mainnet

Token Address: 0xd70408b34ed121722631d647d37c4E6641Ec363D

Network Explorer Link: https://etherscan.io/address/0xd70408b34ed121722631d647d37c4E6641Ec363D

Is a Super Token? true

Address of Underlying Token:  0xa117000000f279D81A1D3cc75430fAA017FA5A2e

SVG Logo Link: https://drive.google.com/file/d/15gcTeWkCAxCyzNYK2Z0V8tPSILWTZVaj/view?usp=sharing

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/aragon

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #16d1f8

Info on Listing: Listing ANTx to test next generation vesting packages for Aragon

Please close only after token has been added to resolver!

**Comment by msoni89** [comment]
![image](https://user-images.githubusercontent.com/65469737/223972171-1965b419-d0b7-4cc3-bf28-b2f2aa33a864.png)


Unable to access Svg image, sent the request.
