### ISSUE TITLE
Dashboard Token Listing: ARMY 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#143]
Discord Handle of Submitter: Fran | Superfluid#3671

Token Symbol: ARMY

Network: Mumbai (testnet)

Token Address: 0x6C357412329f9a3EE07017Be93ed0aC551faa77b

Network Explorer Link: https://mumbai.polygonscan.com/address/0x6C357412329f9a3EE07017Be93ed0aC551faa77b

Is a Super Token? true

Address of Underlying Token:  None

SVG Logo Link: https://keyboard.cool/assets/Twemoji/2694.svg

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): 0

Token HEX Color: #ccd6dd

Info on Listing: https://github.com/kobuta23/king-of-the-hill

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/mumbai/supertokens/0x6C357412329f9a3EE07017Be93ed0aC551faa77b?tab=streams
