### ISSUE TITLE
Dashboard Token Listing: CASH 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#144]
Discord Handle of Submitter: Fran | Superfluid#3671

Token Symbol: CASH

Network: Mumbai (testnet)

Token Address: 0xb891d8559feb358f4651745aaaBFe97067b3bF81

Network Explorer Link: https://mumbai.polygonscan.com/address/0xb891d8559feb358f4651745aaaBFe97067b3bF81

Is a Super Token? true

Address of Underlying Token:  None

SVG Logo Link: https://keyboard.cool/assets/EmojiOneLarge/1f4b0.png

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): 0

Token HEX Color: #e9ba52

Info on Listing: https://github.com/kobuta23/king-of-the-hill

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/mumbai/supertokens/0xb891d8559feb358f4651745aaaBFe97067b3bF81?tab=streams
