### ISSUE TITLE
Dashboard Token Listing: SWIV 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#145]
Discord Handle of Submitter: 0xbf30461210b37012783957d90dc26b95ce3b6f2d

Token Symbol: SWIV

Network: Ethereum Mainnet

Token Address: 0xbf30461210b37012783957d90dc26b95ce3b6f2d

Network Explorer Link: https://etherscan.io/token/0xbf30461210b37012783957D90dC26B95Ce3b6f2d

Is a Super Token? true

Address of Underlying Token:  https://etherscan.io/token/0x8f6f22a962899ade3c46627df45d4a05622cebf2

SVG Logo Link: https://drive.google.com/file/d/1e3eh_l46-EWqYttTk_hFSgA1snSazhKd/view?usp=sharing

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/swivel-governance

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #0078FF

Info on Listing: To clarify -- 
The underlying token: https://etherscan.io/token/0xbf30461210b37012783957D90dC26B95Ce3b6f2d
The deployed super token: https://etherscan.io/token/0x8f6f22a962899ade3c46627df45d4a05622cebf2

Please close only after token has been added to resolver!

**Comment by JTraversa** [comment]
My corrected discord handle: Julian | Swivel#6740
