### ISSUE TITLE
Dashboard Token Listing: IOTX 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#147]
Discord Handle of Submitter: ququzone#4399

Token Symbol: IOTX

Network: Polygon

Token Address: 0xe1c042c91fa08875323e57978c9b9fb413297cf2

Network Explorer Link: https://polygonscan.com/address/0xe1c042c91fa08875323e57978c9b9fb413297cf2

Is a Super Token? true

Address of Underlying Token:  0xf6372cdb9c1d3674e83842e3800f2a62ac9f3c66

SVG Logo Link: https://github.com/iotexproject/iotex-media-kits/blob/main/Token%20Icon/IOTEX-primary-token.svg

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/iotex

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #34ecb8

Info on Listing: IoTeX is a fast, secure, and decentralized platform that connects real world devices, data, and utility to blockchain dApps.

Please close only after token has been added to resolver!

**Comment by vmichalik** [comment]
listed, will be closed by #140
