### ISSUE TITLE
Dashboard Token Listing: CIOTX 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#152]
Discord Handle of Submitter: raullen

Token Symbol: CIOTX

Network: Polygon

Token Address: 0x7f078f02a77e91e67ee592faed23d1cfcb390a60

Network Explorer Link: https://polygonscan.com/token/0x7f078f02a77e91e67ee592faed23d1cfcb390a60

Is a Super Token? true

Address of Underlying Token:  0x300211def2a644b036a9bdd3e58159bb2074d388

SVG Logo Link: https://drive.google.com/drive/u/4/folders/1tX4zXzyBr4ojpeeF-gxpSHJwBYITTvrw

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/iotex

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #18a39e

Info on Listing: IoTeX Foundation is working with superfluid.

Please close only after token has been added to resolver!

**Comment by vmichalik** [comment]
token is listed pending icon assets that are differentiated from existing listing
correct coingecko ID is here: crosschain-iotx

**Comment by vmichalik** [comment]
correct icon is here:
correct coingecko ID is: crosschain-iotx
![CIOTXx](https://user-images.githubusercontent.com/12459761/231111506-c5f8e232-0706-47b8-9457-46ee106b908a.svg)

@msoni89 please add
