### ISSUE TITLE
Dashboard Token Listing: BEPRO 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#159]
Discord Handle of Submitter: Hélder Vasconcelos#2344

Token Symbol: BEPRO

Network: Polygon

Token Address: 0x07CC1cC3628Cc1615120DF781eF9fc8EC2feAE09

Network Explorer Link: https://polygonscan.com/token/0x07cc1cc3628cc1615120df781ef9fc8ec2feae09

Is a Super Token? true

Address of Underlying Token:  0x0b524b829d243df5f70c81aa9f95e32851a57902

SVG Logo Link: https://storage.googleapis.com/taikai-storage/press/bepro/logo/SVG/Bepro_Logo_Light.svg

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: bepro-network

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #4250e4

Info on Listing: To make payments for service providers and employees and future use on our protocol

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
SuperToken: 0x0b524B829D243Df5f70C81AA9f95e32851A57902
Underlying: 0x07CC1cC3628Cc1615120DF781eF9fc8EC2feAE09
listing done: https://console.superfluid.finance/matic/supertokens/0x0b524B829D243Df5f70C81AA9f95e32851A57902?tab=streams

@msoni89 pls add assets
