### ISSUE TITLE
Dashboard Token Listing: USDT 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#164]
Discord Handle of Submitter: Defi_ant#4741

Token Symbol: USDT

Network: Polygon

Token Address: 0x00fA3405a6BbD94549f3B4855A9736766C4f237E

Network Explorer Link: https://polygonscan.com/address/0x00fa3405a6bbd94549f3b4855a9736766c4f237e

Is a Super Token? false

Address of Underlying Token:  

SVG Logo Link: https://cryptologos.cc/logos/tether-usdt-logo.svg?v=024

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/tether

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #54ac94

Info on Listing: The address I added is the USDTx address that I created. 

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/matic/supertokens/0x00fA3405a6BbD94549f3B4855A9736766C4f237E?tab=streams
