### ISSUE TITLE
Dashboard Token Listing: SLINGx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#168]
Discord Handle of Submitter: MikeEmb#7729

Token Symbol: SLINGx

Network: Polygon

Token Address: 0x673d41ebc2b499d3545e5a0309124cd94eda3fb0

Network Explorer Link: https://polygonscan.com/token/0x673d41ebc2b499d3545e5a0309124cd94eda3fb0

Is a Super Token? true

Address of Underlying Token:  0xfc9fa9771145fbb98d15c8c2cc94b837a56d554c

SVG Logo Link: https://slingshotdao.com/slingShotdao-icon-regular-500px-150x150.png

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): $0.0138

Token HEX Color: #021c7b

Info on Listing: Slingshot DAO is a project that allows game ideas to be submitted and voted on by the community. Winning ideas at the end of a period are funded and built. The community members get SLING token rewards for voting on the ideas and the winning idiator gets a large SLING reward, vested over a period of time, as well as some USDC. We intend to use Superfluid to stream tokens to the winning ideators.

Please close only after token has been added to resolver!

**Comment by vmichalik** [comment]
Token listed, assets pending review of #169
