### ISSUE TITLE
[Super Token Listing Request] SMILE

### ISSUE THREAD

**Issue by markcarey** [superfluid-finance/assets#174]
**Project infos and contact (Website, Email, Telegram and/or Twitter handle):**
Hackathon project enabling sending streams to token-bound accounts linked to Lens profiles, using the (hosted) Superfluid subscriptions widget. This token submission is for Goerli, but production version will be on Polygon. Web (work-in-progress): https://tokenbound.social Twitter: @mthacks Email = my first name AT my firstnamelastname DOT com. Discord: @markcarey

**Link to the verified Super Token contract on a Block Explorer:**
https://goerli.etherscan.io/address/0x4632C3cF0da61db0e561DEAc37aCf93a9EBFe789 (Note: this a *custom* super token, not a wrapped ERC20. I have not found a way to verify custom/native super tokens, but happy to do so if anyone can provide guidance.  If it helps for this submission, the contract deployed as part of _this_ transaction sent to a verified contract: https://goerli.etherscan.io/tx/0x483822e132cea4ee451dbf62bd373dac8d722cd7a0bf1e9786297d6bc3af69de The target contract in this txn shows the solidity deployment code for the native/custom super token)

**Link to a logo of the token in SVG (preferred) or PNG format:**
https://tokenbound.social/images/smile.svg

**Link to the coingecko entry of the token:**
n/a

_If not listed on coingecko, please provide a default token price (in USD) to be used in the Dashboard_
0.01 USD

**Comment by markcarey** [comment]
> regarding verification, does this help? https://github.com/superfluid-finance/custom-supertokens#verification

Interesting. I am using Hardhat though ;) Is there an equivalent to `custom-proxy` for Hardhat?  (When I do proxies -- usually minimal "clones" -- I just verify the implementation contract and then all proxies deployed are automatically verified...)

**Comment by vmichalik** [comment]
Listed!

**Comment by d10r** [comment]
> Interesting. I am using Hardhat though ;) Is there an equivalent to `custom-proxy` for Hardhat? (When I do proxies -- usually minimal "clones" -- I just verify the implementation contract and then all proxies deployed are automatically verified...)

There's not, but I found this: https://github.com/NomicFoundation/hardhat/issues/1166

**Comment by markcarey** [comment]
> > Interesting. I am using Hardhat though ;) Is there an equivalent to `custom-proxy` for Hardhat? (When I do proxies -- usually minimal "clones" -- I just verify the implementation contract and then all proxies deployed are automatically verified...)
> 
> There's not, but I found this: [NomicFoundation/hardhat#1166](https://github.com/NomicFoundation/hardhat/issues/1166)

This worked, kinda.  Received: `{"status":"1","message":"OK","result":"The proxy's (0x4632C3cF0da61db0e561DEAc37aCf93a9EBFe789) implementation contract is found at 0x8bd17c30d7750eb1cb245a3157dffd7ca2b5228e and is successfully updated."}` message. This seems to have enabled the "Read as Proxy" and "Write as Proxy" functions on Etherscan, but the "Code" section still shows the bytecode ¯\_(ツ)_/¯

**Comment by d10r** [comment]
@markcarey for the code of the proxy itself to be shown, I assume you have to verify the proxy code against the proxy address.
When running `truffle verify ... --custom-proxy UUPSProxy` with the truffle verification plugin, it will 
* verify the proxy contract against the proxy address
* verify the implementation contract against the implementation address (which it automatically fetches from the proxy)
* trigger the explorer's API call which enables "seeing through" the proxy (read/write proxy tabs)

This "magic" has advantages and disadvantages (see e.g. https://github.com/rkalis/truffle-plugin-verify/issues/178).

In hardhat, afaik the same can be achieved, just not with a single command.
If I find some time, I'll add a hardhat project to the custom-supertokens repo which includes verification.
