### ISSUE TITLE
[Super Token Listing Request] 

### ISSUE THREAD

**Issue by Seroxdesign** [superfluid-finance/assets#176]
**Project infos and contact (Website, Email, Telegram and/or Twitter handle):**

Metagame:
https://metagame.wtf

**Link to the verified Super Token contract on a Block Explorer:**

https://polygonscan.com/token/0x1bd951a9c9a5ec665abef684425f025dc8738cca

**Link to a logo of the token in SVG (preferred) or PNG format:**

https://static.metaswap.codefi.network/api/v1/tokenIcons/137/0xeaecc18198a475c921b24b8a6c1c1f0f5f3f7ea0.png

_(Or upload the logo here)_

![0xeaecc18198a475c921b24b8a6c1c1f0f5f3f7ea0](https://github.com/superfluid-finance/assets/assets/69639595/fefe986d-249c-4b9c-aabc-bb0927c8b01b)

**Link to the coingecko entry of the token:**

https://www.coingecko.com/en/coins/metagame

_If not listed on coingecko, please provide a default token price (in USD) to be used in the Dashboard_

**Comment by d10r** [comment]
listing done, asset PR: https://github.com/superfluid-finance/assets/pull/179
