### ISSUE TITLE
Dashboard Token Listing: FICHx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#177]
Discord Handle of Submitter: pato_molina

Token Symbol: FICHx

Network: Mumbai (testnet)

Token Address: 0x9acb4aff21c88ec743aade1f2a6c5fa623e675c2

Network Explorer Link: https://mumbai.polygonscan.com/tx/0x080d8fdad608668558cc91c2aec1d403902addb45db884e6e04dc785f151f4a3

Is a Super Token? true

Address of Underlying Token:  0xe1f67d2683a3ea352047dc2c71c3ec6b1f7bd4bf

SVG Logo Link: https://upload.wikimedia.org/wikipedia/commons/9/9f/34-gon-dissection-random.svg

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): $1.00

Token HEX Color: #2596be

Info on Listing: This is a test token. We would like to have it listed so we can try different vesting/unlocking schedules for investors, advisors and team members (before trying with the real token ;-))

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done, assets PR ready: https://github.com/superfluid-finance/assets/pull/178
