### ISSUE TITLE
Dashboard Token Listing: XOC 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#182]
Discord Handle of Submitter: JaiBo0217

Token Symbol: XOC

Network: Polygon

Token Address: 0x36d9a149895d905D117C38F3090f4344B76Ec9F4

Network Explorer Link: https://polygonscan.com/token/0x36d9a149895d905d117c38f3090f4344b76ec9f4

Is a Super Token? true

Address of Underlying Token:  0xa411c9Aa00E020e4f88Bc19996d29c5B7ADB4ACf

SVG Logo Link: https://ipfs.io/ipfs/Qmf586WEGkgxQPzJmU2JxvA3pf1D9ck7ttifo3cASWuHDX?filename=xoc%20logo.png

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): $20.00

Token HEX Color: #873e23

Info on Listing: Xocolatl is a stablecoin pegged to the MXN peso with a similar sturcture to DAI where you overr-collateralize a position in XOC using assets like wETH, wstETH, MATIC, MaticX. Visit https://xocolatl.finance/ for more info on the protocol and to play arouund with it.

Please close only after token has been added to resolver!

**Comment by vmichalik** [comment]
[Listed in resolver](https://console.superfluid.finance/matic/supertokens/0x36d9a149895d905D117C38F3090f4344B76Ec9F4?tab=streams), needs PR for assets

**Comment by iafhurtado** [comment]
Hi @d10r , just following up on this issue, could you help me create the PR to include XOCx for assets please? Thanks in advance!

**Comment by d10r** [comment]
PR at https://github.com/superfluid-finance/assets/pull/184

**Comment by vmichalik** [comment]
completed
