### ISSUE TITLE
[Super Token Listing Request] 

### ISSUE THREAD

**Issue by Seroxdesign** [superfluid-finance/assets#183]
**Project infos and contact (Website, Email, Telegram and/or Twitter handle):**

https://www.circle.com/en/usdc-multichain/arbitrum

**Link to the verified Super Token contract on a Block Explorer:**

https://arbiscan.io/token/0xf7d2d79eb2209ba5b499a8156bc60189d2bd9266

**Link to a logo of the token in SVG (preferred) or PNG format:**

_(Or upload the logo here)_

![usd-coin-usdc-logo](https://github.com/superfluid-finance/assets/assets/69639595/8c2ea94d-8351-459b-8a8f-7b2782efcb40)

**Link to the coingecko entry of the token:**

https://www.coingecko.com/en/coins/usd-coin

_If not listed on coingecko, please provide a default token price (in USD) to be used in the Dashboard_

**Comment by d10r** [comment]
@Seroxdesign may it be that your intention was to create a wrapper for the natively issued USDC?
The SuperToken you created wraps the one bridged from Ethereum. We already have a listed wrapper for that, see https://console.superfluid.finance/arbitrum-one/supertokens/0x1dbc1809486460dcd189b8a15990bca3272ee04e?tab=streams

In case you want to wrap the native USDC, that's at https://arbiscan.io/token/0xaf88d065e77c8cc2239327c5edb3a432268e5831
