### ISSUE TITLE
[Super Token Listing Request] USDbCx on Base

### ISSUE THREAD

**Issue by bertux** [superfluid-finance/assets#186]
**Project infos and contact (Website, Email, Telegram and/or Twitter handle):**
https://help.coinbase.com/en/coinbase/getting-started/crypto-education/usd-base-coin

**Link to the verified Super Token contract on a Block Explorer:**
https://basescan.org/address/0x5eacf6a1256d71182df319b38fddec30e23c5851#code

**Link to a logo of the token in SVG (preferred) or PNG format:**
https://basescan.org/token/images/usdbc_ofc_32.png

**Link to the coingecko entry of the token:**
https://www.coingecko.com/en/coins/bridged-usd-coin-base/

**Comment by vmichalik** [comment]
Hey @bertux I'm afraid there is already a listed USDbC on base https://console.superfluid.finance/base-mainnet/supertokens/0x4db26c973fae52f43bd96a8776c2bf1b0dc29556?tab=streams
