### ISSUE TITLE
[Super Token Listing Request] DAIx on Base

### ISSUE THREAD

**Issue by bertux** [superfluid-finance/assets#187]
**Project infos and contact (Website, Email, Telegram and/or Twitter handle):**
https://makerdao.com/

**Link to the verified Super Token contract on a Block Explorer:**
https://basescan.org/address/0x708169c8c87563ce904e0a7f3bfc1f3b0b767f41#code

**Link to a logo of the token in SVG (preferred) or PNG format:**
https://basescan.org/token/images/daistablecoin_32.png

**Link to the coingecko entry of the token:**
https://www.coingecko.com/en/coins/dai/

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/base-mainnet/supertokens/0x708169c8C87563Ce904E0a7F3BFC1F3b0b767f41?tab=streams
