### ISSUE TITLE
[Super Token Listing Request] 

### ISSUE THREAD

**Issue by Codegnosis** [superfluid-finance/assets#188]
Dashboard Token Listing: FUNDx

Discord Handle of Submitter: Codegnosis

Token Symbol: FUNDx

Network: Sepolia

Token Address: 0x783fDEAB6951504C4601184587AaFED01511ED24

Network Explorer Link: https://sepolia.etherscan.io/address/0x783fDEAB6951504C4601184587AaFED01511ED24

Is a Super Token? true

Address of Underlying Token: 0xAfE70A1985ebDefbDCaeedba045d66091C38E1B1

SVG Logo Link: https://raw.githubusercontent.com/unification-com/assets/v1.0.0/icons/svg/unification_icon_blue_circle.svg

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/unification

Harcoded Price (if Coingecko ID is unavailable):

Token HEX Color: #008ed4

Info on Listing: Unification Foundation is working with Superfluid.

**Comment by d10r** [comment]
listed. Not shown in the console due to the subgraph having an issue with changing factory proxies.
