### ISSUE TITLE
[Super Token Listing Request] FUNDx on Ethereum Mainnet

### ISSUE THREAD

**Issue by Codegnosis** [superfluid-finance/assets#189]
**Project infos and contact (Website, Email, Telegram and/or Twitter handle):**
Website: https://unification.com/
Twitter: https://twitter.com/UnificationUND
Telegram: https://t.me/unificationfoundation
Discord: https://discord.com/channels/725618617525207042

**Link to the verified Super Token contract on a Block Explorer:**
https://etherscan.io/address/0x479347DfD0Be56f2a5F7bB1506bFD7AB24d4BA26

**Link to a logo of the token in SVG (preferred) or PNG format:**
https://raw.githubusercontent.com/unification-com/assets/v1.0.0/icons/svg/unification_icon_blue_circle.svg

**Link to the coingecko entry of the token:**
https://www.coingecko.com/en/coins/unification

**Comment by vmichalik** [comment]
This is completed
