### ISSUE TITLE
[Super Token Listing Request] fxFUNDx on Polygon Mainnet

### ISSUE THREAD

**Issue by Codegnosis** [superfluid-finance/assets#190]
**Project infos and contact (Website, Email, Telegram and/or Twitter handle):**
Website: https://unification.com/
Telegram: https://t.me/unificationfoundation
Discord: https://discord.com/channels/725618617525207042
Twitter: https://twitter.com/UnificationUND

**Link to the verified Super Token contract on a Block Explorer:**
https://polygonscan.com/address/0xf1e073d53AF781966F23B1a3B2D9E67cbbA69B92

**Link to a logo of the token in SVG (preferred) or PNG format:**
https://raw.githubusercontent.com/unification-com/assets/v1.0.0/icons/svg/unification_icon_blue_circle.svg

**Link to the coingecko entry of the token:**
https://www.coingecko.com/en/coins/unification

**Comment by vmichalik** [comment]
This is completed
