### ISSUE TITLE
[Super Token Listing Request] Super Giveth Token

### ISSUE THREAD

**Issue by divine-comedian** [superfluid-finance/assets#193]
**Project infos and contact (Website, Email, Telegram and/or Twitter handle):**
https://giveth.io
mitch@giveth.io
@divine_comedian

**Link to the verified Super Token contract on a Block Explorer:**
https://optimistic.etherscan.io/address/0x4caB5B9930210E2EdC6A905B9C75D615872A1A7E
**Link to a logo of the token in SVG (preferred) or PNG format:**
https://raw.githubusercontent.com/Giveth/giveth-design-assets/9fc25bfcd4a04cae53ceaecb8f96e5db738ff8a5/02-logos/GIV%20Token/GIVToken_128x128.svg
_(Or upload the logo here)_

**Link to the coingecko entry of the token:**
https://raw.githubusercontent.com/Giveth/giveth-design-assets/9fc25bfcd4a04cae53ceaecb8f96e5db738ff8a5/02-logos/GIV%20Token/GIVToken_128x128.svg
_If not listed on coingecko, please provide a default token price (in USD) to be used in the Dashboard_

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/optimism-mainnet/supertokens/0x4caB5B9930210E2EdC6A905B9C75D615872A1A7E?tab=streams

**Comment by divine-comedian** [comment]
> listing done: https://console.superfluid.finance/optimism-mainnet/supertokens/0x4caB5B9930210E2EdC6A905B9C75D615872A1A7E?tab=streams

Yahooo! u da best :D
