### ISSUE TITLE
Dashboard Token Listing: WARU 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#195]
Discord Handle of Submitter: xbi0_0

Token Symbol: WARU

Network: Polygon

Token Address: 0xFA3872970c1952741C518B33f1DcE815f55Dc00A

Network Explorer Link: https://discord.com/channels/962352288557563955/962476019627995176/971484191759929364

Is a Super Token? false

Address of Underlying Token:  

SVG Logo Link: https://waruprotocol.one/assets/logo.94e2b55c.png

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.geckoterminal.com/polygon_pos/pools/0x5250525a8fd922ec87b42c42b0ea71fd46565cb0

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #6cebae

Info on Listing: streaming to TBA ( nft smart wallet addresses

WARUx upgrade
https://polygonscan.com/tx/0x1487566d603a328541a786c098d60980325e3ea22bdc9d9bc3b390e278060f16

https://polygonscan.com/token/0x5034f401716a6ceb26c8232fb5640075508085af

https://console.superfluid.finance/matic/supertokens/0x5034f401716a6ceb26c8232fb5640075508085af?tab=streams 

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done, but isn't picked up by the subgraph. Currently can't tell why (transfer event was also triggered).

**Comment by vmichalik** [comment]
is now listed in console
