### ISSUE TITLE
Dashboard Token Listing: REVVx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#196]
Discord Handle of Submitter: _h0ppa

Token Symbol: REVVx

Network: Polygon

Token Address: 0xe0d1978033ee7cf12a8246da7f173f9441b769b0

Network Explorer Link: https://polygonscan.com/token/0xe0d1978033ee7cf12a8246da7f173f9441b769b0

Is a Super Token? true

Address of Underlying Token:  0x70c006878a5A50Ed185ac4C87d837633923De296

SVG Logo Link: Please use exisiting

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/revv

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #f50631

Info on Listing: Distributrion of REVV to OG participants

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done
