### ISSUE TITLE
Dashboard Token Listing: eXOFx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#197]
Discord Handle of Submitter: bertux.celo

Token Symbol: eXOFx

Network: Celo

Token Address: 0x06b6e03bc9711eeb58d5a381a476019e19fddec4

Network Explorer Link: https://celoscan.io/address/0x06b6e03bc9711eeb58d5a381a476019e19fddec4

Is a Super Token? true

Address of Underlying Token:  0x73F93dcc49cB8A239e2032663e9475dd5ef29A08

SVG Logo Link: https://app.mento.org/_next/static/media/eXOF.96a9bf26.svg

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): 0.0017

Token HEX Color: #2596be

Info on Listing: For SuperTontine project I'm helping to stream eXOF in https://en.wikipedia.org/wiki/Rotating_savings_and_credit_association

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done
