### ISSUE TITLE
Dashboard Token Listing: GHOx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#198]
Discord Handle of Submitter: 0xkamal7#0

Token Symbol: GHOx

Network: Ethereum Mainnet

Token Address: 0x22064a21FEE226D8fFB8818E7627d5FF6D0Fc33a

Network Explorer Link: https://sepolia.etherscan.io/token/0x22064a21fee226d8ffb8818e7627d5ff6d0fc33a

Is a Super Token? true

Address of Underlying Token:  0xc4bF5CbDaBE595361438F8c6a187bDc330539c60

SVG Logo Link: https://assets.coingecko.com/coins/images/30663/large/ghoaave.jpeg?1696529533

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/gho

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #2596be

Info on Listing: GHO is the native token of AAVE and by listing this on the dashboard. It would nice to stream GHOx Super Tokens.

Please close only after token has been added to resolver!

**Comment by kamalbuilds** [comment]
@philipandersson @philipandersson @d10r  @seliqui please review .

**Comment by d10r** [comment]
it's now listed, see https://console.superfluid.finance/eth-sepolia/supertokens/0x22064a21FEE226D8fFB8818E7627d5FF6D0Fc33a?tab=streams
