### ISSUE TITLE
Dashboard Token Listing: BLEU 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#216]
Discord Handle of Submitter: @agustife

Token Symbol: BLEU

Network: Base

Token Address: 0xbf4db8b7a679f89ef38125d5f84dd1446af2ea3b

Network Explorer Link: https://basescan.org/token/0xbf4db8b7a679f89ef38125d5f84dd1446af2ea3b

Is a Super Token? true

Address of Underlying Token:  0xbf4db8b7a679f89ef38125d5f84dd1446af2ea3b

SVG Logo Link: https://lebleuelefant.com/bleu.png

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: le-bleu-elefant

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #03C3DF

Info on Listing: working on self-staking BLEU to get BLEUx rewards

Please close only after token has been added to resolver!

**Comment by vmichalik** [comment]
Correct Super Token address is here https://console.superfluid.finance/base-mainnet/supertokens/0x04fFB9ce95af003A3AA3611be6c6Ca1431151FB5?tab=streams

**Comment by vmichalik** [comment]
assets added, waiting for onchain listing

**Comment by vmichalik** [comment]
Listed. closing https://console.superfluid.finance/base-mainnet/supertokens/0x04fFB9ce95af003A3AA3611be6c6Ca1431151FB5?tab=streams
