### ISSUE TITLE
Dashboard Token Listing: RORx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#219]
Discord Handle of Submitter: jon.bray.eth

Token Symbol: RORx

Network: Base

Token Address: 0x307d8225C6428A1E505f824b1c97CF9127351f0c

Network Explorer Link: https://basescan.org/address/0x307d8225C6428A1E505f824b1c97CF9127351f0c

Is a Super Token? true

Address of Underlying Token:  0x9e13480a81Af1Dea2f255761810Ef8d6CbF21735

SVG Logo Link: https://aquamarine-evil-bedbug-307.mypinata.cloud/ipfs/QmYWu8exywwMwEmPcFt3ztmURRFc9Z8KTnAY4f6784oRUR

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: rorschach

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #040404

Info on Listing: creating a staking pool with real-time payments, and would like to stream future allocations to prevent large token unlocks

Please close only after token has been added to resolver!

**Comment by kasparkallas** [comment]
It should be handled already.
