### ISSUE TITLE
Dashboard Token Listing: TREE 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#220]
Discord Handle of Submitter: nezz9461

Token Symbol: TREE

Network: Base

Token Address: 0x65e9B4Ae7885BD3E4e1CC4f280863b859d231FC2

Network Explorer Link: https://basescan.org/address/0x65e9B4Ae7885BD3E4e1CC4f280863b859d231FC2

Is a Super Token? true

Address of Underlying Token:  0x6888c2409D48222E2CB738eB5a805A522a96CE80

SVG Logo Link: https://imgur.com/UEilIbS

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: treeplanting

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #7AA229

Info on Listing: Farcaster community, want to use supertokens to rent adland ad spaces in their own native currency: https://warpcast.com/~/channel/treeplanting

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/base-mainnet/supertokens/0x65e9B4Ae7885BD3E4e1CC4f280863b859d231FC2?tab=streams
