### ISSUE TITLE
Dashboard Token Listing: SLING 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#221]
Discord Handle of Submitter: Imrul | the__accountant

Token Symbol: SLING

Network: Arbitrum

Token Address: 0x5F8a7c646511A790C53F171891E5d469cA884EdE

Network Explorer Link: https://arbiscan.io/address/0x5F8a7c646511A790C53F171891E5d469cA884EdE

Is a Super Token? false

Address of Underlying Token:  

SVG Logo Link: https://drive.google.com/file/d/154gqDCJb0k3w13oMseB9eQQwAVaozZCW/view?usp=sharing

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: slingshot

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #051b7b

Info on Listing: Both SLING and Super SLING to be listed:

SLING address given above, however for the wrapped super token - Super SLING (SLINGx), the token address link is: https://arbiscan.io/address/0xb44df234e068F62a9A18b6Be6543de28D5a7312F

We previously had SLING listed on Superfluid on Polygon. We've migrated since and are essentially redoing this formality to be able to continue streams.

Project: slingshotdao.com

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/arbitrum-one/supertokens/0xb44df234e068F62a9A18b6Be6543de28D5a7312F?tab=streams

**Comment by vmichalik** [comment]
assets already in the repo too, closing as complete
