### ISSUE TITLE
Dashboard Token Listing: ZURFx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#222]
Discord Handle of Submitter: danielbv#1017

Token Symbol: ZURFx

Network: Polygon

Token Address: 0xc3fA1E27A2A58Ee476F04D4f4867F06b6E906Cc5

Network Explorer Link: https://polygonscan.com/token/0xc3fa1e27a2a58ee476f04d4f4867f06b6e906cc5

Is a Super Token? true

Address of Underlying Token:  0x8906365c65589e87870040d681e51a69e9c6f91e

SVG Logo Link: https://drive.google.com/file/d/1nQ0Wf79CoRA1efWUa-0g4f3ehqT3M5WC/view?usp=sharing

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: zurf

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #00FFFF

Info on Listing: We are building a social media app with video and livestreams for Lens and Farcaster users. 

Twitter: https://x.com/zurfSocial
Available on:
Android: t.ly/VOrp6
iOS: https://testflight.apple.com/join/9vAjdPl7
Gitbook:https://zurfsocial.gitbook.io/zurf

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://explorer.superfluid.finance/matic/supertokens/0xc3fA1E27A2A58Ee476F04D4f4867F06b6E906Cc5?tab=streams

**Comment by vmichalik** [comment]
listed onchain and assets available, pending /tokenlist PR
