### ISSUE TITLE
Dashboard Token Listing: USDGLO 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#235]
Discord Handle of Submitter: @lanzdingz 

Token Symbol: USDGLO

Network: Optimism

Token Address: 0x9F41d0AA24E599fd8D0c180Ee3C0F609dc41c622

Network Explorer Link: https://optimistic.etherscan.io/tx/0x00622c9d3203ee4f83395ecd165ec052dc1d30ebe637f12a637cfbe556f77eb9

Is a Super Token? true

Address of Underlying Token:  0x4f604735c1cf31399c6e711d5962b2b3e0225ad3

SVG Logo Link: https://drive.google.com/file/d/1mYM4RQ2Nbm5VHcH-pztlaxDT-ERsl-Uf/view?usp=sharing

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/glo-dollar

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #24e5df

Info on Listing: Giveth wants us to be a streaming donation option for them and we want to be used in other grant and payout streams 

glodollar.org

We are a stablecoin that funds web3 public goods and IRL causes by donating 100% of our profits

We will be wrapping our token on Eth, Base, Polygon, Arbitrum and Celo, but we wanted to make sure we did it correctly with Optimism first before wrapping the token on the other chains (https://www.glodollar.org/articles/smart-contract-addresses)

Thank you

Please close only after token has been added to resolver!

**Comment by vmichalik** [comment]
listing, pending PR to /tokenlist @kasparkallas
