### ISSUE TITLE
Dashboard Token Listing: XOCx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#236]
Discord Handle of Submitter: Jaibo0217

Token Symbol: XOCx

Network: Base

Token Address: 0xedF89f2612a5B07FEF051e1a0444342B5410C405

Network Explorer Link: 
https://basescan.org/address/0xedf89f2612a5b07fef051e1a0444342b5410c405

Is a Super Token? true

Address of Underlying Token:  [0xa411c9Aa00E020e4f88Bc19996d29c5B7ADB4ACf](https://basescan.org/address/0xa411c9aa00e020e4f88bc19996d29c5b7adb4acf)

SVG Logo Link: https://ipfs.io/ipfs/Qmf586WEGkgxQPzJmU2JxvA3pf1D9ck7ttifo3cASWuHDX?filename=xoc%20logo.png

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): 0,052

Token HEX Color: #6A372B

Info on Listing: this is our project behind the XOC stablecoin https://xocolatl.finance

Please close only after token has been added to resolver!

**Comment by vmichalik** [comment]
done, pending PR to https://github.com/superfluid-finance/tokenlist
