### ISSUE TITLE
Dashboard Token Listing: $mferx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#238]
Discord Handle of Submitter: Elvijs Dzirkals#1408

Token Symbol: $mferx

Network: Base

Token Address: 0x9097E4A4D75A611b65aB21d98A7D5b1177C050F7

Network Explorer Link: https://basescan.org/address/0x9097E4A4D75A611b65aB21d98A7D5b1177C050F7

Is a Super Token? true

Address of Underlying Token:  0xe3086852a4b125803c815a158249ae468a3254ca

SVG Logo Link: https://assets.coingecko.com/coins/images/36550/standard/mfercoin-logo.png?1711876821

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: mfercoin

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #FEFEFF

Info on Listing: mferx listing

Please close only after token has been added to resolver!

**Comment by vmichalik** [comment]
listed, assets ready, waiting for tokenlist
