### ISSUE TITLE
Dashboard Token Listing: Super Nounspace 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#239]
Discord Handle of Submitter: Elvijs Dzirkals#1408

Token Symbol: Super Nounspace

Network: Base

Token Address: 0x4E395eC7b71Dd87A23dD836edb3eFE15A6c2002B

Network Explorer Link: https://basescan.org/address/0x4E395eC7b71Dd87A23dD836edb3eFE15A6c2002B

Is a Super Token? true

Address of Underlying Token:  0x48c6740bcf807d6c47c864faeea15ed4da3910ab

SVG Logo Link: https://space.nounspace.com/branding/info-dashboard-logo.png

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: nounspace

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #FEFEFF

Info on Listing: Super Nounspace listing

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
already listed: https://explorer.superfluid.finance/base-mainnet/supertokens/0x4E395eC7b71Dd87A23dD836edb3eFE15A6c2002B?tab=streams

**Comment by vmichalik** [comment]
listed, assets ready, waiting for tokenlist
