### ISSUE TITLE
Dashboard Token Listing: ONCHAINx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#242]
Discord Handle of Submitter: gravenp

Token Symbol: ONCHAINx

Network: Base

Token Address: 0xcc6bce523c20f582daaf0ccafaae981df46ceb41

Network Explorer Link: https://basescan.org/token/0xcc6bce523c20f582daaf0ccafaae981df46ceb41

Is a Super Token? true

Address of Underlying Token:  0xfef2d7b013b88fec2bfe4d2fee0aeb719af73481

SVG Logo Link: https://assets.coingecko.com/coins/images/36948/standard/IMG_2072.jpeg?1712896843

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: onchain

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #1d201f

Info on Listing: We're going to launch a build-a-thon with Guild next week using the Frontier Guild/Council Haus GDA setup and a new Flow State UI. There will be lots of new ONCHAINx holders that might be interested in using SuperBoring too!

Please close only after token has been added to resolver!

**Comment by vmichalik** [comment]
listed in subgraph
