### ISSUE TITLE
[Super Token Listing Request] Degen Dogs WOOFx (Degen Chain)

### ISSUE THREAD

**Issue by markcarey** [superfluid-finance/assets#244]
**Project infos and contact (Website, Email, Telegram and/or Twitter handle):**

Degen Dogs
https://warpcast.com/~/channel/degendogs
https://degendogs.club
https://x.com/degendogsclub

This is a wrapped version of the MintClub-deployed bonding curve token to be used for Degen Dogs Mission 2, as described at https://docs.google.com/presentation/d/1scmjVVeYegkzYfs0vrYvWA7cZuPFBD7SngXqyyAcH0I/edit?usp=sharing

**Link to the verified Super Token contract on a Block Explorer:**

Degen chain:
https://explorer.degen.tips/address/0x58E90e043Fe47d224CC475349992A90317ACBD69

**Link to a logo of the token in SVG (preferred) or PNG format:**

https://degendogs.club/img/woof.png

**Link to the coingecko entry of the token:**
_If not listed on coingecko, please provide a default token price (in USD) to be used in the Dashboard_

$0.000005355 (current price on the mint club bonding curve) 🤷‍♂️

**Comment by d10r** [comment]
Listed: https://explorer.superfluid.finance/degen/supertokens/0x58E90e043Fe47d224CC475349992A90317ACBD69?tab=streams

WOOF!

**Comment by markcarey** [comment]
Thank you for the quick response!

What is expected timeframe for the token logo to start appearing in the app? (No rush, just curious)

<img width="821" alt="Cursor_and_WOOFx___Superfluid" src="https://github.com/user-attachments/assets/a8ba57b0-8330-4810-a665-85e1bf367e4c">

**Comment by kasparkallas** [comment]
<img width="387" alt="Screenshot 2024-11-20 at 14 19 00" src="https://github.com/user-attachments/assets/1ea30519-d031-4fa4-9c16-899024732929">

<img width="968" alt="image" src="https://github.com/user-attachments/assets/db70f2e3-b11c-4679-af5f-6d348e4153cb">

Available in tokenlist 5.1.2: https://www.npmjs.com/package/@superfluid-finance/tokenlist/v/5.12.0
