### ISSUE TITLE
Dashboard Token Listing: jEUR 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#245]
Discord Handle of Submitter: pascaljarvis.network

Token Symbol: jEUR

Network: Base

Token Address: 0xfcdecfe37463912c03a644128eb02a1147715e36

Network Explorer Link: https://basescan.org/token/0xfcdecfe37463912c03a644128eb02a1147715e36

Is a Super Token? true

Address of Underlying Token:  0x4154550f4Db74Dc38d1FE98e1F3F28ed6daD627d

SVG Logo Link: https://drive.google.com/file/d/1FDHlpC7jEsg8NRHE0afm9oAV0vgGB-dW/view?usp=share_link

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): 1 euro

Token HEX Color: #003399

Info on Listing: Using to stream rewards for our staked jEUR token

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listed: https://explorer.superfluid.finance/base-mainnet/supertokens/0xfCDecfe37463912C03A644128EB02A1147715E36?tab=streams
