### ISSUE TITLE
Dashboard Token Listing: sDAIx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#247]
Discord Handle of Submitter: decentralix

Token Symbol: sDAIx

Network: Gnosis Chain

Token Address: 0xD30Aa2F6fC32c4DC8Bf3Bd5994d89c8F9e81FCD1

Network Explorer Link: https://gnosisscan.io/address/0xD30Aa2F6fC32c4DC8Bf3Bd5994d89c8F9e81FCD1

Is a Super Token? true

Address of Underlying Token:  0xaf204776c7245bF4147c2612BF6e5972Ee483701

SVG Logo Link: https://assets.coingecko.com/coins/images/32066/standard/sDAI_Logo_%281%29.png?1696530863

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: savings-xdai

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #F5AC37

Info on Listing: sDAI is basically a better version of DAI, so it would be cool to stream my friend sDAI that bears some yield instead of just xDAI

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://explorer.superfluid.finance/xdai/supertokens/0xD30Aa2F6fC32c4DC8Bf3Bd5994d89c8F9e81FCD1?tab=streams
