### ISSUE TITLE
Dashboard Token Listing: USD+ 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#58]
Discord Handle of Submitter: maximlafe#8401

Token Symbol: USD+

Network: Polygon

Token Address: 0x236eeC6359fb44CCe8f97E99387aa7F8cd5cdE1f

Network Explorer Link: https://polygonscan.com/token/0x236eeC6359fb44CCe8f97E99387aa7F8cd5cdE1f

Is a Super Token? true

SVG Logo Link: https://imgur.com/a/FpeXn24

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): $1

Token HEX Color: 001845

**Comment by maximlafe** [comment]
CG is available as well https://www.coingecko.com/en/coins/usdplus

**Comment by sunnyjaycer** [comment]
Is this actually a Super Token or just a plain ERC20? It appears to be the latter from your submission. What are the benefits have making this token render on the Dashboard?

**Comment by maximlafe** [comment]
Hey @sunnyjaycer, thanks for getting back to me.
We support 'ERC20 wrapper super token' https://github.com/ovnstable/ovnstable-app/blob/master/pkg/core/contracts/StaticUsdPlusToken.sol. 

USD+ is a USDC pegged stablecoin that yields daily profit to its holders just for holding it! It works by taking all the leg work out for the holder and automatically reinvesting itself into other reward-yielding stablecoin strategies.
The user can freeze his money in USD+ at Superfluid at the begging of the month and he'll get a daily profit before he'll make payments at the end of the month.

**Comment by maximlafe** [comment]
@sunnyjaycer do you have updates by any chance?

**Comment by sunnyjaycer** [comment]
Hey @maximlafe, could you please verify the contract at https://polygonscan.com/address/0xD81d9D5e1378593A63f979E3f6A9A43041e91eEf#code? This way we can know that it is in fact a streamable super token

**Comment by vmichalik** [comment]
@maximlafe Super Token wrappers don't play well with rebasing tokens at the moment, so I wouldn't advise continuing to pursue a listing with this. Feel free to join our Discord and start a deeper discussion if we can support you working out how to handle it!

**Comment by vmichalik** [comment]
Closing this for now, please feel free to reopen to continue the conversation or move to discord @maximlafe
