### ISSUE TITLE
[Super Token Listing Request] Super USD Coin (Optimism)

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/assets#65]
**Project infos and contact (Website, Email, Telegram and/or Twitter handle):**
USD Coin https://www.circle.com/en/usdc

**Link to the verified Super Token contract on a Block Explorer:**
https://optimistic.etherscan.io/address/0x8430f084b939208e2eded1584889c9a66b90562f

**Link to a logo of the token in SVG (preferred) or PNG format:**

_(Or upload the logo here)_

**Link to the coingecko entry of the token:**
https://www.coingecko.com/en/coins/usd-coin

_If not listed on coingecko, please provide a default token price (in USD) to be used in the Dashboard_
1

**Comment by d10r** [comment]
https://console.superfluid.finance/optimism-mainnet/supertokens/0x8430f084b939208e2eded1584889c9a66b90562f?tab=streams
