### ISSUE TITLE
Dashboard Token Listing: wUSD+ 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#70]
Discord Handle of Submitter: maximlafe#8401

Token Symbol: wUSD+

Network: Polygon

Token Address: 0x4e36D8006416EA1d939A0EeaE73AFDAcA86BD376

Network Explorer Link: https://polygonscan.com/token/0xfec31BC5e213615b013Eb58f1B8185868Ee4BD12

Is a Super Token? true

SVG Logo Link: https://svgshare.com/s/jCR

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): 1

Token HEX Color: FCCA46

Please close only after token has been added to resolver!

**Comment by sunnyjaycer** [comment]
We're going to hold off on listing this for the below reasons:

- You’re trying to list a non-Super Token which has little value for listing as users won’t be able to do anything Superfluid with it. We would prefer to not spend time on this
- It appears the basis of what you do want to make Superfluid-compatible is a rebasing token. The Superfluid Protocol does not support rebasing tokens (it conflicts heavily with balance calculation). If you do manage to deploy a wrapper for a rebasing token, it will not work the way you intend it and would not be something we'd support listing
