### ISSUE TITLE
Dashboard Token Listing: COW 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#80]
Discord Handle of Submitter: 0x0mb#5267

Token Symbol: COW

Network: Gnosis Chain

Token Address: 0x177127622c4A00F3d409B75571e12cB3c8973d3c

Network Explorer Link: https://blockscout.com/xdai/mainnet/address/0x177127622c4A00F3d409B75571e12cB3c8973d3c

Is a Super Token? true

Address of Underlying Token:  https://blockscout.com/xdai/mainnet/tx/0x8719c5bc508864ec7c3d49cfb87015ad4cbb3706b029204b82349628cefe6f0a

SVG Logo Link: https://ipfs.io/ipfs/Qmc5KLdrRmADMoYW91hT7WdyBueMEY84cG5k5o9kBGKof4

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/cow-protocol

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #000000

Info on Listing: The primary use is for using the COW token in the COW GrantsDAO, to pay the committee members by streaming COW tokens.

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
correction:
Super Token: 0xaC945dC430ceF2BB8FB78B3cb5fbC936dD2C8ab6
Underlying Token: 0x177127622c4A00F3d409B75571e12cB3c8973d3c

listing done
