### ISSUE TITLE
Dashboard Token Listing: SAVEx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#84]
Discord Handle of Submitter: goldenageguide#5455

Token Symbol: SAVEx

Network: Gnosis Chain

Token Address: 0x83ccc929c1131d2d18b001c05cfeed9f3364a506

Network Explorer Link: https://blockscout.com/xdai/mainnet/address/0x83cCC929C1131d2d18b001C05CFeED9f3364a506/token-transfers#address-tabs

Is a Super Token? true

Address of Underlying Token:  0x338D4527c9E7F7316c43581684Bc510b851F832a

SVG Logo Link: https://drive.google.com/file/d/1bdmU7h8BPH2hTP7D_cQIk96hXCNK3o_K/view?usp=sharing

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): 10

Token HEX Color: #59a21a

Info on Listing: Save Impact Dao.   Save money, Save the planet.   All Rights Reserved 2022 By Adbongo Group LLC www.adbongo.io  

Zero Waste Protocol White Paper: https://docs.google.com/document/d/1j2klDUYwekXK10Tm-kyU-dPfseaCmicKn8RTYtOupSY/edit?usp=sharing

Discord:  https://discord.gg/Ym4xcdPVqA

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
Resolver listing done in https://blockscout.com/xdai/mainnet/tx/0xe5dd0c3f1affce3f75b72199cd1bf823d3a9abea8f60fa7dee7a769c5eb7ab2a

See https://console.superfluid.finance/xdai/supertokens/0x83ccc929c1131d2d18b001c05cfeed9f3364a506?tab=streams
