### ISSUE TITLE
Dashboard Token Listing: ART 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#85]
Discord Handle of Submitter: rsp#9882

Token Symbol: ART

Network: Polygon

Token Address: 0xD7F3aaC7557c213b035C19Bd89bd693396accCD6

Network Explorer Link: https://polygonscan.com/address/0xD7F3aaC7557c213b035C19Bd89bd693396accCD6

Is a Super Token? true

Address of Underlying Token:  https://polygonscan.com/address/0xd98a3eabb78a759868d5a35677ffa99a78f33ec7

SVG Logo Link: https://drive.google.com/file/d/19DhJrwzvIhGi1J7fHhJky9TboUSaAB9J/view

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): $0.06

Token HEX Color: #1acc6c

Info on Listing: The Artizen Fund for human creativity awards monthly grants to creators who play at the intersection of art, tech, science, and design. Our $ART token gives ownership of the fund to our community. We would like to us SuperFluid to stream $ART tokens to our core contributes and community members. You can find out more about us and our mission here: https://www.artizen.fund/

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done.  
Note that the Super Token address is 0xd98A3EaBB78a759868d5a35677fFA99A78F33Ec7, while the underlying token address is 0xD7F3aaC7557c213b035C19Bd89bd693396accCD6
