### ISSUE TITLE
Dashboard Token Listing: XSGD 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#87]
Discord Handle of Submitter: RDS#0042

Token Symbol: XSGD

Network: Polygon

Token Address: 0xDC3326e71D45186F113a2F448984CA0e8D201995

Network Explorer Link: https://polygonscan.com/token/0xDC3326e71D45186F113a2F448984CA0e8D201995

Is a Super Token? true

Address of Underlying Token:  https://polygonscan.com/address/0x2c90719f25b10fc5646c82da3240c76fa5bccf34

SVG Logo Link: https://drive.google.com/file/d/16KelshvhLGOs_PULBd_WzdTKEAJhm35G/view?usp=sharing

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/xsgd/

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #1048e5

Info on Listing: We are a Singapore-dollar backed stablecoin issuer, one of the largest non-USD backed stablecoins in the world, and have seen interest from our community for real-time money streaming services through our stablecoins. Superfluid is a great alternative for us to expand the use case of our stablecoins. 

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
The provided token address is not correct, points to the SuperToken logic.  
There's 2 deployments wrapping XSDG:
1.  https://console.superfluid.finance/matic/supertokens/0x2a51cd1bc3da6f005809e9eb97c17ae62c8b3143?tab=indexes
2.  https://console.superfluid.finance/matic/supertokens/0x49765f8fcf0a1cd4f98da906f0974a9085d43e51?tab=indexes

I asked sukalpomitra#4870 who seems to be the deployer, didn't get an answer yet.

**Comment by d10r** [comment]
0x49765f8fcf0a1cd4f98da906f0974a9085d43e51 is now listed:
https://console.superfluid.finance/matic/supertokens/0x49765f8fcf0a1cd4f98da906f0974a9085d43e51

**Comment by ryandesouza** [comment]
<img width="524" alt="Screenshot 2022-12-01 at 10 24 49 AM" src="https://user-images.githubusercontent.com/44060153/204950898-f38bb095-6978-41d6-b527-e0d92c1ea890.png">

Thanks for listing the token @d10r ! I was wondering if it's possible to include the XSGD logo on the wrap/unwrap tab. (See screenshot) Currently, the token logo is only visible on the bridge tab. Thank you!
