### ISSUE TITLE
Dashboard Token Listing: ROTIx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#88]
Discord Handle of Submitter: wuzgutwuzgut#1239

Token Symbol: ROTIx

Network: Polygon

Token Address: 0xB7d60973cC27324Dcae837d89d7Bd9c5f15e3833

Network Explorer Link: https://polygonscan.com/address/0xb7d60973cc27324dcae837d89d7bd9c5f15e3833

Is a Super Token? true

Address of Underlying Token:  0x13B4bd4c0719F9F46df35Bfc234213b4Df6E9B7c

SVG Logo Link: https://d18vdu4p71yql0.cloudfront.net/libraries/twemoji/1f35e.svg

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): $0.25

Token HEX Color: #e28743

Info on Listing: ROTI is served to distinguish our casual and hardcore listeners/fans. Token is used to mint our exclusive NFT to allow them access to a gated website for our exclusive music releases. We also offer them to claim merchandise using ROTI. This token at the moment is only relevant within our audience/super fans. Our goal is to build a grassroot ecosystem from the ground up. 

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
done
