### ISSUE TITLE
Dashboard Token Listing: KHIZA 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#90]
Discord Handle of Submitter: WagnerMB#3032

Token Symbol: KHIZA

Network: Polygon

Token Address: 0x25856d46748ee959f99a0fbbb5312c73473cb533

Network Explorer Link: https://polygonscan.com/address/0x25856d46748ee959f99a0fbbb5312c73473cb533

Is a Super Token? false

Address of Underlying Token:  

SVG Logo Link: https://drive.google.com/file/d/1qYiVlrJvrZw14yAiwYMe8NIRuR0u2LuR/view?usp=sharing

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): 0.04

Token HEX Color: #101424

Info on Listing: Hey Guys! We're a Brazilian DAO Venture Builder for Web3. We just got some funds from FFF, hired a great team, and now we're exploring some thesis to build upon on it. All team will receive Khiza tokens as part of salary, and this is why we need Superfluid accepting Khiza. Let's build together?

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
is now listed: https://console.superfluid.finance/matic/supertokens/0xa6810e06fb8c93b2C53C0D6415c885719CBA6EB5?tab=streams
