### ISSUE TITLE
Dashboard Token Listing: Dood 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#91]
Discord Handle of Submitter: arnav#9887

Token Symbol: Dood

Network: Polygon

Token Address: 0x8C36336211916C58860f1EDf20B0F50eA66D8bd5

Network Explorer Link: https://polygonscan.com/address/0x8C36336211916C58860f1EDf20B0F50eA66D8bd5

Is a Super Token? false

Address of Underlying Token:  

SVG Logo Link: https://drive.google.com/file/d/1rRMEhNQ6tM8z6QVnXYfoOSCktb5sBgYf/view?usp=share_link

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): $0.16

Token HEX Color: #2596be

Info on Listing: We want to experiment with streaming of a fractional NFT using superfluid. This NFT is a doodle which has been bridged from ETH to Polygon and fractionalized on Polygon, the tokens created are erc20 tokens. After testing of this passes, we can use this model with other partner NFT collections where they use streaming to reward team members.

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
this request was missing the SuperToken address, handled in a new request: https://github.com/superfluid-finance/assets/issues/97
