### ISSUE TITLE
Dashboard Token Listing: NEARx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#92]
Discord Handle of Submitter: PerseusFX#4917

Token Symbol: NEARx

Network: Polygon

Token Address: 0x094Ed09F072596C34C5c0b197dcEB0da6b04C580

Network Explorer Link: https://polygonscan.com/address/0x094ed09f072596c34c5c0b197dceb0da6b04c580

Is a Super Token? true

Address of Underlying Token:  0x72bd80445b0db58ebe3E8dB056529D4C5FAF6F2f

SVG Logo Link: https://cryptologos.cc/logos/near-protocol-near-logo.svg?v=023

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): $2

Token HEX Color: #000000

Info on Listing: To integrate Superfluid Super token capabilities, CFA, and IDA with the NEAR protocol. NEARx super token can now be used to stream and distribute NEAR tokens and for DeFi integration with Polygon and Aurora networks.

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
Listing done: https://console.superfluid.finance/matic/supertokens/0x094Ed09F072596C34C5c0b197dcEB0da6b04C580?tab=streams
