### ISSUE TITLE
Dashboard Token Listing: rexSHIRT 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#93]
Discord Handle of Submitter: mikeghen

Token Symbol: rexSHIRT

Network: Polygon

Token Address: 0x19cA69C66768B487D28226C0a60Ab2B2aa8E5c5C

Network Explorer Link: https://console.superfluid.finance/matic/supertokens/0x19ca69c66768b487d28226c0a60ab2b2aa8e5c5c

Is a Super Token? true

Address of Underlying Token:  NA

SVG Logo Link: https://ricochet-frontend-git-rexshirt-lp-mikeghen.vercel.app/static/media/rexshirt.a3000188.svg

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: NA, soon

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #79aad9

Info on Listing: This is a supertoken being auctioned off on the Ricochet Launchpad. rexSHIRT tokens are redeemable for Ricochet T-Shirts. Redemption happens in person.

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/matic/supertokens/0x19ca69c66768b487d28226c0a60ab2b2aa8e5c5c?tab=streams
