### ISSUE TITLE
Dashboard Token Listing: rexHAT 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#94]
Discord Handle of Submitter: Mike Ghen

Token Symbol: rexHAT

Network: Polygon

Token Address: 0xe91D640fCAEA9602CF94C0d48A251a7f6d946953

Network Explorer Link: https://polygonscan.com/address/0xe91D640fCAEA9602CF94C0d48A251a7f6d946953

Is a Super Token? true

Address of Underlying Token:  NA

SVG Logo Link: https://drive.google.com/file/d/18jJkDqRpPaVRioJc-yLZpOmipdZFJGCO/view?usp=sharing

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): NA

Token HEX Color: Please use what I used for rexSHIRT

Info on Listing: I tried to verify this myself with Didi's truffle verify method in the custom-supertoken repo, but it failed with this error: 

```
(base) mikeghen@Michaels-iMac custom-supertokens % npx truffle run --network matic verify BurnMintSuperToken@0xe91D640fCAEA9602CF94C0d48A251a7f6d946953 --custom-proxy BurnMintSuperToken
Verifying BurnMintSuperToken@0xe91D640fCAEA9602CF94C0d48A251a7f6d946953
Verifying custom proxy contract BurnMintSuperToken at 0xe91D640fCAEA9602CF94C0d48A251a7f6d946953
Verifying proxy implementation BurnMintSuperToken at 0x0928392705e7224a8299c7a346fcf38ec5142abb
Fail - Unable to verify
Failed to verify 1 contract(s): BurnMintSuperToken@0xe91D640fCAEA9602CF94C0d48A251a7f6d946953
```

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
now listed: https://console.superfluid.finance/matic/supertokens/0xe91D640fCAEA9602CF94C0d48A251a7f6d946953?tab=streams

Verification had failed bcs the canonical SuperToken logic wasn't verified on Polygon. I fixed that and re-run this command, the token is now verified.

@msoni89 please add the logo and close the issue.
