### ISSUE TITLE
Dashboard Token Listing: CRKx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#95]
Discord Handle of Submitter: tmoindustries#0001

Token Symbol: CRKx

Network: Polygon

Token Address: 0xe88F7C019Dd3feb5e738681730fb150E62814670

Network Explorer Link: https://polygonscan.com/address/0xe88f7c019dd3feb5e738681730fb150e62814670

Is a Super Token? true

Address of Underlying Token:  0xf122a63f9fd807fa28a3495ad822ad84c934793d

SVG Logo Link: https://drive.google.com/file/d/1dNpebZbuqXLJwrZ9h1ILg4Rn2aLyv3hk/view?usp=sharing

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): 1

Token HEX Color: #4bbcfb

Info on Listing: Discussed with your team Monday.  $CRK is our internal token for basin.global.  We are linking a series of Safes together with our .basin NFT contract running Charged Particles to then Stream value.  Our flow of value mimics the Water Cycle in nature.

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listed: https://console.superfluid.finance/matic/supertokens/0xe88F7C019Dd3feb5e738681730fb150E62814670?tab=streams

@msoni89 please add icon and close
