### ISSUE TITLE
Dashboard Token Listing: SIGNAL 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#96]
Discord Handle of Submitter: Fancy・RADAR#4355

Token Symbol: SIGNAL

Network: Polygon

Token Address: 0x9b532fFa57631d77163BE75E965E6AdFc3b81510

Network Explorer Link: https://polygonscan.com/token/0x9b532ffa57631d77163be75e965e6adfc3b81510?a=0x7D35eab5F5fdF6b458B18c29D0D61092835F9e99

Is a Super Token? true

Address of Underlying Token:  0x7D35eab5F5fdF6b458B18c29D0D61092835F9e99

SVG Logo Link: https://drive.google.com/file/d/1QVUXtIGCOWaiienp4rPsvYtKxWFdXHgO/view?usp=drive_fs

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): $1.50

Token HEX Color: #06427b

Info on Listing: We listed at the beginning of the community to vest early contributors over 6 months, now we want to unwrap all the tokens so we can view holders and amounts on chain.

Thank you!

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
note that the token addresses are the wrong way round,  0x7D35eab5F5fdF6b458B18c29D0D61092835F9e99 is the SuperToken and 0x9b532ffa57631d77163be75e965e6adfc3b81510 is the underlying.

Listing done: https://console.superfluid.finance/matic/supertokens/0x7D35eab5F5fdF6b458B18c29D0D61092835F9e99?tab=streams
