### ISSUE TITLE
Dashboard Token Listing: Super Dood 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#97]
Discord Handle of Submitter: _mundhrakeshav#3296

Token Symbol: Super Dood

Network: Polygon

Token Address: 0xFdCC5C161A296F3ecCE3112d066192f88375390b

Network Explorer Link: https://polygonscan.com/address/0xFdCC5C161A296F3ecCE3112d066192f88375390b

Is a Super Token? true

Address of Underlying Token:  0x8c36336211916c58860f1edf20b0f50ea66d8bd5

SVG Logo Link: https://cdn.simplehash.com/assets/50f69167346d31f05a19d12f91c18b506dce5e7f02e8ae238d04f442ee3ea64e.png

Coingecko or Hardcoded Price?: Hardcoded

Coingecko ID: 

Harcoded Price (if Coingecko ID is unavailable): $0.143146

Token HEX Color: #9ae3ff

Info on Listing: We want to experiment with streaming of a fractional NFT using superfluid. This NFT is a doodle which has been bridged from ETH to Polygon and fractionalized on Polygon, the tokens created are erc20 tokens. After testing of this passes, we can use this model with other partner NFT collections where they use streaming to reward team members.

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing undone because of non-canonical token symbol
