### ISSUE TITLE
Dashboard Token Listing: DAIx 

### ISSUE THREAD

**Issue by SFServer** [superfluid-finance/assets#99]
Discord Handle of Submitter: Elvijs Dzirkals #1408

Token Symbol: DAIx

Network: Binance Smart Chain

Token Address: https://www.bscscan.com/address/0x1e38baa2735128bcc23792ff9aae96ea7aa7ecd2

Network Explorer Link: https://www.bscscan.com/address/0x1e38baa2735128bcc23792ff9aae96ea7aa7ecd2

Is a Super Token? true

Address of Underlying Token:  https://www.bscscan.com/token/0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3

SVG Logo Link: We already have DAIx assets 

Coingecko or Hardcoded Price?: Coingecko

Coingecko ID: https://www.coingecko.com/en/coins/dai

Harcoded Price (if Coingecko ID is unavailable): 

Token HEX Color: #F5AC37.

Info on Listing: Mr Latvia needs this for testing stuff apart from the only BNB token we have listed

Please close only after token has been added to resolver!

**Comment by d10r** [comment]
listing done: https://console.superfluid.finance/bnb-smart-chain/supertokens/0x1e38baa2735128bcc23792ff9aae96ea7aa7ecd2?tab=streams
